#!/bin/bash
# Episodic ledger writer.
# Appends ONE episode record (a JSON object on one line) to
# memory/episodes/YYYY-MM.jsonl and keeps memory/episodes/INDEX.md fresh
# (deterministic: prepend the newest one-liner, truncate to the cap).
#
# Invoked from command steps (/wrap-up Step 5c, /safe-clear Step 4c), never
# from a lifecycle event, and safe to call manually:
#
#   bash .claude/hooks/episode-append.sh \
#     --task "one line: what this session was doing" \
#     --outcome success|partial|fail \
#     --domain "short domain label" \
#     --files "path/a.md,path/b.ts" \
#     --decision "one line: the load-bearing decision" \
#     --lesson "optional one line: what to do differently"
#
# Guarantees:
#   - Pure shell. Uses jq when available for JSON encoding, degrades to a
#     built-in escaper when jq is absent. No other dependencies.
#   - Never fails the calling command: always exits 0, even on bad input.
#   - Deterministic INDEX maintenance: the file is fully rebuilt each call
#     (title + blank + newest-first entries, hard cap 18 entries = 20 lines).
#
# Load policy (see /recall): INDEX.md may be loaded into context (20-line
# cap). The JSONL episode files are grep/tail territory ONLY and are never
# loaded whole.

DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
EPISODES_DIR="$DIR/memory/episodes"
INDEX="$EPISODES_DIR/INDEX.md"
MONTH_FILE="$EPISODES_DIR/$(date +"%Y-%m").jsonl"
TS=$(date +"%Y-%m-%dT%H:%M:%S")
DAY=$(date +"%Y-%m-%d")
INDEX_CAP=18

TASK=""
OUTCOME=""
DOMAIN=""
FILES=""
DECISION=""
LESSON=""

while [ $# -gt 0 ]; do
  case "$1" in
    --task)     TASK="${2:-}"; shift 2 || break ;;
    --outcome)  OUTCOME="${2:-}"; shift 2 || break ;;
    --domain)   DOMAIN="${2:-}"; shift 2 || break ;;
    --files)    FILES="${2:-}"; shift 2 || break ;;
    --decision) DECISION="${2:-}"; shift 2 || break ;;
    --lesson)   LESSON="${2:-}"; shift 2 || break ;;
    *) shift ;;
  esac
done

# Nothing worth recording without at least a task line.
if [ -z "$TASK" ]; then
  echo "episode-append: no --task given, nothing recorded." >&2
  exit 0
fi

# Coerce the outcome into the closed set; unknown values degrade to partial.
case "$OUTCOME" in
  success|partial|fail) : ;;
  *) OUTCOME="partial" ;;
esac
[ -z "$DOMAIN" ] && DOMAIN="general"

mkdir -p "$EPISODES_DIR" 2>/dev/null || exit 0

# ── JSON encoding ────────────────────────────────────────────────
# json_str: escape backslash, double quote, tab, and strip newlines/CRs.
json_str() {
  printf '%s' "$1" | tr -d '\n\r' | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e "s/$(printf '\t')/\\\\t/g"
}

# files: comma-separated list -> JSON array of strings.
files_json() {
  local out="" item first=1
  local rest="$1,"
  while [ -n "$rest" ]; do
    item="${rest%%,*}"
    rest="${rest#*,}"
    # trim surrounding spaces
    item=$(printf '%s' "$item" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
    [ -z "$item" ] && continue
    if [ "$first" = "1" ]; then first=0; else out="$out,"; fi
    out="$out\"$(json_str "$item")\""
  done
  printf '[%s]' "$out"
}

if command -v jq >/dev/null 2>&1; then
  LINE=$(jq -cn \
    --arg ts "$TS" --arg task "$TASK" --arg outcome "$OUTCOME" \
    --arg domain "$DOMAIN" --arg files "$FILES" \
    --arg decision "$DECISION" --arg lesson "$LESSON" \
    '{ts:$ts, task:$task, outcome:$outcome, domain:$domain,
      files:($files | split(",") | map(gsub("^\\s+|\\s+$";"")) | map(select(length > 0))),
      decision:$decision}
     + (if ($lesson | length) > 0 then {lesson:$lesson} else {} end)' 2>/dev/null)
fi

if [ -z "${LINE:-}" ]; then
  LINE="{\"ts\":\"$TS\",\"task\":\"$(json_str "$TASK")\",\"outcome\":\"$OUTCOME\",\"domain\":\"$(json_str "$DOMAIN")\",\"files\":$(files_json "$FILES"),\"decision\":\"$(json_str "$DECISION")\""
  if [ -n "$LESSON" ]; then
    LINE="$LINE,\"lesson\":\"$(json_str "$LESSON")\"}"
  else
    LINE="$LINE}"
  fi
fi

echo "$LINE" >> "$MONTH_FILE" 2>/dev/null || exit 0

# ── INDEX maintenance (deterministic prepend + truncate) ─────────
# One-liner format: - [YYYY-MM-DD] outcome | domain | task (task capped at 90 chars).
SHORT_TASK=$(printf '%s' "$TASK" | tr -d '\n\r' | head -c 90)
NEW_ENTRY="- [$DAY] $OUTCOME | $DOMAIN | $SHORT_TASK"

TMP_INDEX=$(mktemp 2>/dev/null) || exit 0
{
  echo "# Episode Index (auto-generated by episode-append.sh, newest first)"
  echo ""
  echo "$NEW_ENTRY"
  if [ -f "$INDEX" ]; then
    grep '^- \[' "$INDEX" 2>/dev/null | head -$((INDEX_CAP - 1))
  fi
} > "$TMP_INDEX" 2>/dev/null
mv "$TMP_INDEX" "$INDEX" 2>/dev/null || rm -f "$TMP_INDEX"

echo "episode-append: recorded [$OUTCOME] $DOMAIN episode in memory/episodes/$(basename "$MONTH_FILE")"
exit 0
